### ISSUE TITLE
BAD_NETWORK

### ISSUE THREAD

**Issue by dragonfire535** [matheuss/google-translate-api#11]
{ Error
     at /app/node_modules/google-translate-api/index.js:105:17
     at process._tickCallback (internal/process/next_tick.js:109:7) code: 'BAD_NETWORK' }

This occurs at every translation request.

**Comment by mikhailrojo** [comment]
it happens to me too

**Comment by AStoker** [comment]
Likewise. If we're all getting this, it's most likely a change on Google's side :(

**Comment by mikhailrojo** [comment]
I debugged a little and it seems to me that 'safe-eval' module works strange
like it filters more then it supposed to and we end up in catch statement

**Comment by monodrom** [comment]
Also getting it.

**Comment by dragonfire535** [comment]
```
if (err.statusCode !== undefined && err.statusCode !== 200) {
    e.code = 'BAD_REQUEST';
} else {
    e.code = 'BAD_NETWORK';
```
Seems like any error code that's not `undefined` or `200` is `BAD_NETWORK`

**Comment by JukeboxRhino** [comment]
I too am getting this error. Any fixes?

**Comment by dragonfire535** [comment]
Why would it be checking for specifically undefined in the first place.

**Comment by JukeboxRhino** [comment]
I've opened a pull request to fix it

**Comment by Ajaja** [comment]
403 https://translate.google.com/translate_a/single
Google has just closed the door.

**Comment by LukasNavickas** [comment]
Are you guys going to fix it??

**Comment by teamsteamdev** [comment]
Don't worry, 403 is just an authentication error. 

Using @JukeboxRhino changes _everything still works_.

**Comment by myfrndjk** [comment]
hi,

is it fixed.
I downloaded from npm i google-translate-api

```
const translate = require('google-translate-api');
 
translate('Ik spreek Engels', {to: 'en'}).then(res => {
    console.log(res.text);
    //=> I speak English 
    console.log(res.from.language.iso);
    //=> nl 
}).catch(err => {
    console.error(err);
});
```
unfortunately the above sample code is throwing error

Thanks
Jk

**Comment by anubi** [comment]
I grabbed teamsteamdev 's pull request (removing undefined checks) and I still receive a BAD_NETWORK request using the basic 'Ik spreek Engels' test.

**Comment by aman-raikwar** [comment]
Hello guys!

Did you got the solution for the BAD_NETWORK issue. I m getting the same. Please help.

I also tried the solution defined above but no success..

I need it on urgent basis.

**Comment by FrozenCaptain** [comment]
yup its solved https://github.com/arthurlacoste/google-translate-api/commit/ed8c87a016b66f2accb7f82a57a2025ea7411c91 What i did is just copied the whole Index.js 
And it worked!!!! Nice! God bless you. 
https://github.com/arthurlacoste

**Comment by dalezak** [comment]
If you wanted to use @arthurlacoste's commit https://github.com/arthurlacoste/google-translate-api/commit/ed8c87a016b66f2accb7f82a57a2025ea7411c91 directly, you can update your `package.json` to:
```
  "google-translate-api": "git+https://github.com/arthurlacoste/google-translate-api.git#ed8c87a016b66f2accb7f82a57a2025ea7411c91",
```

**Comment by arthurlacoste** [comment]
@dalezak more simple : 
`"google-translate-api": "arthurlacoste/google-translate-api"`

**Comment by srochar** [comment]
or
`"google-translate-api": "https://github.com/arthurlacoste/google-translate-api/archive/master.tar.gz"`

**Comment by prusya** [comment]
@arthurlacoste Could you please also update languages.js file with `'am': 'Amharic'` language added?

**Comment by arthurlacoste** [comment]
Updating languages.js : 
- Adding Amharic
- Correct error (Sudanese > Sundanese)

https://github.com/arthurlacoste/google-translate-api

**Comment by ashwindollar** [comment]
Is there any idea when the node package itself will be updated with this resolution? When I deploy my application, the cloud service provider (Heroku) will likely install this package from npm. That's most likely going to pull down the buggy package directly from npm.

**Comment by JukeboxRhino** [comment]
The only way is if matheuss himself accepts the pull request, unless
somebody wants to fork it and make a new npm package and we can work off
that one.

**Comment by ashwindollar** [comment]
Thanks for the reply @JukeboxRhino. For now Yarn seems to be installing directly from arthurlacoste's GitHub repo so it should probably work with Heroku. It's been 13 days since arthur fixed the bug. How much more time in your opinion do you think it's appropriate wait for the pull request to be approved before someone forks it and people work off the fork?

**Comment by FranklinChen** [comment]
It's been almost a year now since any activity here. I think it's time for us to move on.

**Comment by arthurlacoste** [comment]
I @ashwindollar (and everybody),

I use Heroku too, and NPM provide some feature allowing github repo as a npm package :

With my fork, you can use :
"google-translate-api": "arthurlacoste/google-translate-api"

More info on the NPM doc for Github url :
https://docs.npmjs.com/files/package.json#github-urls

And others services :
https://docs.npmjs.com/files/package.json#repository

But I can create an NPM package, if you want :)

**Comment by ashwindollar** [comment]
Hi @arthurlacoste. I was able to get it working with that change to my package.json.

**Comment by iuccio** [comment]
Just replace:
 (lindex.js ln:87)  
`if (body[7] !== undefined && body[7][0] !== undefined) {`
with
`if (body[7] !== null && body[7][0] !== null) {`

and
(index.js ln:75)
`if (obj[0] !== undefined) {`
with
`if (obj[0] !== null) {`

;-)

**Comment by vagusX** [comment]
@JukeboxRhino you are right, so @matheuss will you fix it?

**Comment by AStoker** [comment]
https://github.com/matheuss/google-translate-api/issues/11#issuecomment-302586764
Time to move on ☹️

**Comment by JukeboxRhino** [comment]
Resolved. https://github.com/matheuss/google-translate-api/pull/27

**Comment by matheuss** [comment]
https://github.com/matheuss/google-translate-api/releases/tag/2.3.0 🙏

**Comment by maurocrmrc** [comment]
Hello everyone. I am trying to use the Translation API together with Google Cloud Functions from Firebase and the following error appears on the server console:

`
{ Error: getaddrinfo ENOTFOUND translate.google.com translate.google.com:443
    at /user_code/node_modules/google-translate-api/node_modules/google-translate-token/index.js:103:25
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  code: 'BAD_NETWORK',
  message: 'getaddrinfo ENOTFOUND translate.google.com translate.google.com:443' }
`

followed by

> Billing account not configured. External network is not accessible and quotas are severely limited. Set up billing account to remove these restrictions

Does the fact that I'm using Firebase influence the operation of the API or did they really restrict access to the service?

Any comment will be welcome.

**Comment by maurocrmrc** [comment]
Hello everyone. How are you? 

I'm trying to use the translation API together with the _Firebase Cloud Functions_ server, and the following error appeared in the console:

`
{Error: getaddrinfo ENOTFOUND translate.google.com translate.google.com:443
    Atus / geo
    At process._tickDomainCallback (internal / process / next_tick.js: 135: 7)
  Code: 'BAD_NETWORK',
  Message: 'getaddrinfo ENOTFOUND translate.google.com translate.google.com:443'}
`

followed by:

`
Billing account not configured. External network is not accessible and quotas are severely limited. Set up billing account to remove these restrictions
`

I am using _Web Components / Polymer_ as the architecture, and the `package.json` of the `/functions` folder (which stores the API functions) has the following configuration: `"google-translate-api": "^ 4.2.1"`

The fact that I'm using Firebase can influence the non-functioning of the API or are they really trying to restrict free access to the service?

Any comment will be welcome.

**Comment by matheuss** [comment]
@maurocrmrc `ENOTFOUND` means `translate.google.com` is not found on the DNS server that is being used. Given you're receiving that other message, looks like Firebase is blocking access to the internet because you didn't configure a billing account.

**Comment by extensionsapp** [comment]
Hey.
Google tightened the restrictions and now from a single IP address can make very few queries.
I added the use of a proxy server (IPv4, IPv6). Maybe my solution will help you.

https://github.com/extensionsapp/translatte

```javascript
const translatte = require('translatte');

// Translate string to English using proxy
translatte('Вы говорите на русском?', {
    from: 'ru',
    to: 'en',
    agents: [
        'Mozilla/5.0 (Windows NT 10.0; ...',
        'Mozilla/4.0 (Windows NT 10.0; ...',
        'Mozilla/5.0 (Windows NT 10.0; ...'
    ],
    proxies: [
        'LOGIN:PASSWORD@192.0.2.100:12345',
        'LOGIN:PASSWORD@192.0.2.200:54321'
    ]
}).then(res => {
    console.log(res);
}).catch(err => {
    console.error(err);
});
// { text: 'Do you speak Russian?', 
//   from: { 
//     language: { 
//       didYouMean: false, 
//       iso: 'ru' 
//     }, 
//     text: { 
//       autoCorrected: false, 
//       value: '', 
//       didYouMean: false 
//     } 
//   },
//   raw: '' }
```
