### ISSUE TITLE
unable to resolve module "querystring"

### ISSUE THREAD

**Issue by Angelk90** [matheuss/google-translate-api#43]
@matheuss: I have installed the latest version, I did as the example but I get the following error:
![screenshot_20171123-205527 1](https://user-images.githubusercontent.com/20476002/33187327-5d0fdcd4-d091-11e7-99ea-dbd36c5fd245.jpg)

**Comment by Angelk90** [comment]
@matheuss : In the package.json file, dependencies lack querystring, it would be very useful to add it.

**Comment by rajat-jain9** [comment]
I have developed an android mobile app using react-native. My native language for the app is English but I want to make it available in Mandarin Chinese also. For this I'm using google-translate-api but While importing google-translate-api, getting an error:-

Error: Unable to resolve module "querystring" from "...". Module "querystring" does not exist in the Haste module map.

**Comment by maple3142** [comment]
I haven't used RN before, but I know that RN doesn't have some node.js builtin modules such as `querystring`,`http`.
Perhaps you need to map some compatible module in place of `querystring`.

**Comment by anwaarul** [comment]
> I have developed an android mobile app using react-native. My native language for the app is English but I want to make it available in Mandarin Chinese also. For this I'm using google-translate-api but While importing google-translate-api, getting an error:-
> 
> Error: Unable to resolve module "querystring" from "...". Module "querystring" does not exist in the Haste module map.

Any answer found?

**Comment by VivekSharma811** [comment]
I am having the same problem. Did anyone find any solution?

**Comment by KundanIws** [comment]
I am also getting this issue. I am using a translator api of google.
