### ISSUE TITLE
Not working in Electron.js？(it suppose)

### ISSUE THREAD

**Issue by 1c7** [matheuss/google-translate-api#49]
it doesn't send any HTTP request at all.
no return error or anything, just silent.

using macOS, Electron v1.7.9

**Comment by 1c7** [comment]
seem like no one maintaining this? last commit is June 2017, now is Dec 2017

**Comment by vitalets** [comment]
So, is it finally worked?

**Comment by 1c7** [comment]
I forgot. because it's chinese new year so I just close a bunch of github issue that been open for years
