### ISSUE TITLE
No support for Punjabi language?

### ISSUE THREAD

**Issue by voidpls** [matheuss/google-translate-api#68]
When attempting to translate to Punjabi, there's no error, yet it returns the English text inputted. 
<img width="481" alt="vmau6 1" src="https://user-images.githubusercontent.com/28279553/40457943-40709dc4-5ec7-11e8-80bc-5e91185105b4.png">
Using Punjabi's ISO code (pa), on the other hand, returns an error.
<img width="482" alt="qdjzi 1" src="https://user-images.githubusercontent.com/28279553/40457972-639a5bf0-5ec7-11e8-96e2-363f885f7add.png">

**Comment by brolnickij** [comment]
@voidpls Hi! Use `'ma'`
`translate('Hello World', {from: 'en', to: 'ma'});`

https://github.com/matheuss/google-translate-api/blob/master/languages.js#L84

**Comment by voidpls** [comment]
@gamexxx 

languages.js 
> The languages that Google Translate supports (as of 5/15/16) alongside with their ISO 639-1 codes

However, Punjabi's ISO 639-1 Code is `'pa'`

[loc.gov](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=pa):
<img width="382" alt="hqgcd 1" src="https://user-images.githubusercontent.com/28279553/40578860-e1333fcc-60e9-11e8-9f5f-9d4354d6a337.png">

[Wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes):
<img width="429" alt="21dwc 1" src="https://user-images.githubusercontent.com/28279553/40578855-bcfbcec6-60e9-11e8-823b-b1b216f43d54.png">

Also, using `'ma'` still translates it English, no matter the starting language.

**Comment by cancamilo** [comment]
I have noticed the same issue. It works replacing with "pa" in langauges file

**Comment by rawr51919** [comment]
I have PRed this fix into a maintained fork of this repo (vitalets/google-translate-api).

**Comment by rawr51919** [comment]
This has been fixed as of v2.8.0 in https://github.com/vitalets/google-translate-api.
