### ISSUE TITLE
503 (SERVICE UNAVAILABLE)

### ISSUE THREAD

**Issue by vreans08** [matheuss/google-translate-api#85]
name:"HTTPError"
stack:"HTTPError\n    at translate (C:\Users\kannanv\Downloads\mean-stack-angular-6-part-4-master\mean-stack-angular-6-part-4-master\backend\node_modules\@k3rn31p4nic\google-translate-api\src\index.js:143:19)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
statusCode:503
statusMessage:"Service Unavailable"

**Comment by wolfgang42** [comment]
This appears to be the same error as #84.
