### ISSUE TITLE
Response code 403 (Forbidden) Error dose not work in node.

### ISSUE THREAD

**Issue by KrunalGosai** [matheuss/google-translate-api#93]
message: 'Response code 403 (Forbidden)',
host: 'translate.google.com',
hostname: 'translate.google.com',
method: 'GET',
path:
'/translate_a/single?client=t&sl=en&tl=nl&hl=nl&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=I%20spea%20Dutch!&tk=377195.377195',
statusCode: 403,
statusMessage: 'Forbidden'

**Comment by vitalets** [comment]
Duplicates to https://github.com/matheuss/google-translate-api/issues/79.
You can also try this fork https://github.com/vitalets/google-translate-api that fixes several issues of original package.

**Comment by KrunalGosai** [comment]
thanks 

https://github.com/vitalets/google-translate-api working great !!
