### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by wonderlandpark** [matheuss/google-translate-api#94]
DOESN'T WORK
```javascript
{ Error
    at C:\Users\wonderlandpark\Desktop\Beta\node_modules\google-translate-api\index.js:105:17
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'BAD_REQUEST' }
```

**Comment by brolnickij** [comment]
@wonderlandpark 
Hello friend! Go to the fork of this repository, which is now actively supported: https://github.com/vitalets/google-translate-api

**Comment by riddla** [comment]
@brolnickij, great stuff! I integrated https://github.com/vitalets/google-translate-api into my fork of this project over at https://github.com/riddla/alfred-polyglot and it works like a charm. My fork can be installed via `https://github.com/riddla/alfred-polyglot`.
